-- MSSQL용 초기 스키마 (문법이 미세하게 다름)
CREATE TABLE NEXUS_USER (
    USER_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    USER_NAME NVARCHAR(100) NOT NULL, -- NVARCHAR 사용
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(50) DEFAULT 'ROLE_USER',
    DEPT_CODE VARCHAR(20)
);

-- 테스트 데이터
INSERT INTO NEXUS_USER (USER_ID, USER_NAME, PASSWORD, ROLE, DEPT_CODE) 
VALUES ('dev_master', '김넥서스', '{noop}1234', 'ROLE_ADMIN', 'DEV001');